apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: demo-shared-resources
  namespace: argocd
spec:
  destination:
    namespace: guestbook-demo-project
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: Application/guestbook
    repoURL: "https://github.com/JiNaL1112/ArgoCD-learing.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
      

    