apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:JiNaL1112/argocd-example-apps.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
  
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    