apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/JiNaL1112/argocd-example-apps.git
  password:  # password goes here, NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops. password is PAT 
  username: JiNaL1112