apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-dev-project
  namespace: argocd
spec: 
  destination: 
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: Application/Guestbook
    repoURL: "https://github.com/JiNaL1112/ArgoCD-learing.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true